name: 'Payara Qube CLI Action'
description: 'Deploy an app to Payara Qube using Payara Qube CLI'
branding:
  icon: 'upload-qube'
  color: 'orange'
inputs:
  token:
    description: 'token obtained from `pcl login --print-token` and stored in secrets'
    required: true
  subscription_name:
    description: 'Optional. Only required if your account has access to multiple subscriptions. Provide the subscription name to specify which subscription to use.'
    required: false
  namespace:
    description: 'The namespace under which the app is deployed'
    required: true
  app_name:
    description: 'The name of the app to deploy'
    required: false
  artifact_location:
    description: 'The location of the artifact (WAR) to deploy'
    required: false
  deploy:
    description: 'Deploy the app'
    required: false
    default: true
  qube_version:
    description: 'Version of Qube CLI to download'
    required: false
    default: '2.0.0'
runs:
  using: 'node12'
  main: 'dist/index.js'
